# Generated by Django 3.0.8 on 2020-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('ticker', models.CharField(max_length=4, null=True)),
                ('campaign_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('email_domain', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EdmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4, null=True)),
                ('domain', models.CharField(max_length=100)),
                ('campaign_id', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('clicked', models.PositiveIntegerField()),
                ('opened', models.PositiveIntegerField()),
                ('delivered', models.PositiveIntegerField()),
                ('bounced', models.PositiveIntegerField()),
                ('complained', models.PositiveIntegerField()),
                ('unsubscribed', models.PositiveIntegerField()),
                ('trans_date', models.DateTimeField()),
            ],
        ),
    ]
