# Generated by Django 3.0.8 on 2020-07-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igstatsapp', '0002_auto_20200703_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntype',
            name='ticker',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
