# Generated by Django 3.0.8 on 2020-07-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igstatsapp', '0003_auto_20200704_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edmdata',
            name='campaign_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igstatsapp.CampaignType'),
        ),
        migrations.AlterField(
            model_name='edmdata',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igstatsapp.Domain'),
        ),
    ]
