# Generated by Django 3.0.8 on 2020-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igstatsapp', '0005_csvdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='edmdata',
            name='total_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
