# Generated by Django 3.0.8 on 2020-07-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igstatsapp', '0007_edmdata_recipient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipient_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='edmdata',
            name='recipient_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igstatsapp.Recipient'),
        ),
    ]
