# Generated by Django 3.0.8 on 2020-07-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igstatsapp', '0008_auto_20200707_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='domain',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
